### ISSUE TITLE
Standardizing the Routers/Controllers

### ISSUE THREAD

**Issue by ethanszeto** [Northeastern-Science-Magazine/nusci-backend#106]
### Task Necessity
- Right now, we have some routes that directly send files and other routes reference controller files. For standard practice, we should have a consistent way of doing things.
### Task Description
- Your task is to change all routes that send files directly, and create controller methods for them (An abstracted solution is welcome! We encourage you to think of ways it can be done with request parameters).

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i'm interesting in this issue if there is no one is currently working on it
