### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by ethanszeto** [Northeastern-Science-Magazine/nusci-backend#109]
### Task Necessity
- Someone forgot their password/ someone realizes their password is kinda bad.
### Task Description
- This is a rather complicated ticket that will require an advanced understanding of endpoints, request parameters, automatic emails, JWT, keys and encryption.
- Your task is to set up, using the email architecture, a system that sends a user an email with a secret key. That secret key can then be used in the reset password endpoint, in order to verify that user, and thus log them in, and send them to the profile page to - reset their password. 
- There should be a reset password endpoint to handle this.
### Auth
- Account Level

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
i like this issue and i would like to work on it if there is no one workeing on it
