### ISSUE TITLE
Create a Cancelled Enum for ArticleStatus

### ISSUE THREAD

**Issue by ethanszeto** [Northeastern-Science-Magazine/nusci-backend#248]
## Task Necessity
- If an author can no longer write this article, and there are no plans to continue writing it for future semesters or other authors, we can effectively call this article `Cancelled`. We need a way to denote this in the codebase.

## Task Description / Solution Requirements
- Your task is to create an enum for ArticleStatus called `Cancelled`. 
- This enum should have the same behaviours as the other ArticleStatus enums

## Authorizations (if applicable)
- N/A

## Test Requirements
- Add additional ArticleStatus enum tests, to handle functions that can be called on ArticleStatus.Cancelled (follow the pattern given in the existing enum test files)
- All tests should pass

## Additional Notes
- N/A

**Comment by kk7188048** [comment]
Can you check the PR. If anything is wrong pls let me know.
Thanks
